### ISSUE TITLE
add `get_streams()` method

### ISSUE THREAD

**Issue by AndrielFR** [akhilnarang/vlrgg-scraper#3]
i would like you to add a method to return the link of the streams and their platforms that are available to watch the match, i can add and make a pr if you want. 🥵

**Comment by akhilnarang** [comment]
https://github.com/akhilnarang/vlrgg-scraper/commit/e23fb7e0205d51314d584ff6cbb972252636c664 should cover it I guess

**Comment by AndrielFR** [comment]
> [e23fb7e](https://github.com/akhilnarang/vlrgg-scraper/commit/e23fb7e0205d51314d584ff6cbb972252636c664) should cover it I guess

oh, thank you, it'll be very useful to me
