### ISSUE TITLE
why do you don't get matches from `/matches` endpoint?

### ISSUE THREAD

**Issue by AndrielFR** [akhilnarang/vlrgg-scraper#4]
the amount of completed matches and upcoming are currently very few, i would like the API to get from its `/matches` endpoint for new matches and `/matches/results` for completed matches and a pagination system in addition to the information: current page and total pages.
of course, this goes for events and its `/events` endpoint too.

**Comment by AndrielFR** [comment]
half part made in https://github.com/akhilnarang/vlrgg-scraper/commit/8e213fd19b8a46a807a0edce45b80353b4868384, only the events and the paging system are missing 🙂

**Comment by akhilnarang** [comment]
Yeah the paging part seems like a pain to implement

**Comment by AndrielFR** [comment]
> Yeah the paging part seems like a pain to implement

ok, i'll do and make a pr, ok?

**Comment by AndrielFR** [comment]
> Yeah the paging part seems like a pain to implement

sad
